# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            The Bentern
tagline:          'A Jekyll theme'
description:      'Debugger of broken apps'
url:              http://thebentern.github.io
baseurl:          /
comments:         true

author:
  name:           'Ben Meadors'
  url:            http://thebentern.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
